name: Build and Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Massa node release version"
        required: true

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          build-args: VERSION=${{ inputs.version }}
          platforms: linux/amd64, linux/arm64/v8
          push: true
          tags: peterjah/massa-core:dev
          # tags: peterjah/massa-core:${{ inputs.version }}, peterjah/massa-core:latest
